name: Deploy React App to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install awscli
      
      - name: Build React App
        run: |
          npm install
          CI=false npm run build --no-warnings

      - name: Test
        run: |
          npm test
      
      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://sb-ror-react --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 

          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}





# name: Front End Deployment


# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [19]
          
#     steps:
#     - uses: actions/checkout@v1
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - name: NPM Install
#       run: |
#         npm install
#     - name: Production Build
#       run: |
#         npm run build
#     - name: Install aws-cli
#         id: install-aws-cli
#         uses: unfor19/install-aws-cli-action@v1
#         with:
#         version: 2     # default
#         verbose: false # default
#         arch: amd64    # allowed values: amd64, arm64
#         rootdir: ""    # defaults to "PWD"
#         workdir: ""    # defaults to "PWD/unfor19-awscli"
#       - name: Deploy to S3
#         run: |
#           aws s3 sync ./build s3://sb-ror-react
#       uses: jakejarvis/s3-sync-action@master
#       with:
#         args: --acl public-read --delete
#       env:
#         AWS_S3_BUCKET: ${{ env.AWS_PRODUCTION_BUCKET_NAME }}
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_REGION: ${{ secrets.AWS_REGION }}




